

function install()
{
    sudo apt-get install nginx

    # 启动nginx
    systemctl start nginx.service
}

# 如何将所有流量都转发到同一个域名
# http://zengchaowu.com
# http://www.zengchaowu.com
# https://zengchaowu.com
# 全部转发到https://www.zengchaowu.com
server {
    # listen 80 default_server;
    # listen [::]:80 default_server;

    # SSL configuration
    #
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    ssl_certificate conf.d/1_zengchaowu.com_bundle.crt;
    ssl_certificate_key conf.d/2_zengchaowu.com.key;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;
    #
    # Note: You should disable gzip for SSL traffic.
    # See: https://bugs.debian.org/773332
    #
    # Read up on ssl_ciphers to ensure a secure configuration.
    # See: https://bugs.debian.org/765782
    #
    # Self signed certs generated by the ssl-cert package
    # Don't use them in a production server!
    #
    # include snippets/snakeoil.conf;

    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    server_name www.zengchaowu.com;

    location / {
            # First attempt to serve request as file, then
            # as directory, then fall back to displaying a 404.
            try_files $uri $uri/ =404;
    }
}
server {
        listen 80;
        listen [::]:80;
        server_name zengchaowu.com;
        return 301 https://www.$server_name$request_uri;
}

server {
        listen 80;
        listen [::]:80;
        server_name www.zengchaowu.com;
        return 301 https://$server_name$request_uri;
}

server {
        listen 443;
        listen [::]:443;
        server_name zengchaowu.com;
        return 301 https://www.$server_name$request_uri;
}